---
- hosts: spine
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=head-end-replication/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy FRR daemons
      copy: src=head-end-replication/{{ansible_hostname}}/daemons dest=/etc/frr/
    - name: copy FRR conf
      copy: src=head-end-replication/{{ansible_hostname}}/frr.conf dest=/etc/frr/frr.conf
    - name: copy vxsnd conf
      copy: src=head-end-replication/{{ansible_hostname}}/vxsnd.conf dest=/etc/
    - name: reload networking
      command: ifreload -a
    - name: reload frr 
      service: name=frr state=restarted
    - name: reload vxsnd
      service: name=vxsnd state=restarted enabled=true

- hosts: leaf
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=head-end-replication/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: copy FRR daemons
      copy: src=head-end-replication/{{ansible_hostname}}/daemons dest=/etc/frr/
    - name: copy FRR conf
      copy: src=head-end-replication/{{ansible_hostname}}/frr.conf dest=/etc/frr/frr.conf
    - name: copy vxrd conf
      copy: src=head-end-replication/{{ansible_hostname}}/vxrd.conf dest=/etc/
    - name: reload networking
      command: ifreload -a
    - name: reload FRR 
      service: name=frr state=restarted
    - name: reload vxrd
      service: name=vxrd state=restarted enabled=true

- hosts: servers
  become: yes
  tasks:
    - name: copy interfaces
      copy: src=head-end-replication/{{ansible_hostname}}/interfaces dest=/etc/network/
    - name: restarts servers with their new configuration
      shell: sleep 1 && shutdown -r 0
      async: 1
      poll: 0
      ignore_errors: true
    - name: Wait for everything to come back up
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
